name: Continuous Integration
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version: ['7.1', 7.2', '7.3', '7.4', '8.0']
        flags: ['', '--prefer-lowest']
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          coverage: xdebug2
      - run: composer update --prefer-dist --no-interaction ${{ matrix.flags }}
      - run: vendor/bin/atoum
